services:
  imagechurn:
    build: ./app
      
    image: monimagechurn
    container_name: moncontainerchurn
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      
  
  ui:
    image: imagechurn_ui
    build: ./ui
    container_name: churn_ui
    ports:
      - "8501:8501"
    environment:
      API_URL: ${API_URL}
    depends_on:
      - imagechurn

  db:
    image: postgres:15
    container_name: churn_database
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: churn_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d churn_database"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data: